# Generated by Gemini CLI / テストコードを生成させてみた
import pytest
from fastapi.testclient import TestClient
from app.main import app

# TestClientインスタンスを作成
client = TestClient(app)

# `create_or_resume_session` 関数のパス
CHAT_LOGIC_SESSION_PATH = "app.main.create_or_resume_session"

@pytest.mark.asyncio
async def test_new_session_success(mocker):
    """
    POST /new_session エンドポイントの正常系テスト
    - chat_logic.create_or_resume_session をモック化する
    - 新しいセッションが正常に初期化されることを確認する
    """
    # --- モックの設定 ---
    # create_or_resume_session をモック化
    mock_create_session = mocker.patch(CHAT_LOGIC_SESSION_PATH)
    
    # --- テストデータ ---
    request_body = {
        "project": "new_session_project",
        "phase": "new_session_phase"
    }
    
    # --- リクエストの実行 ---
    # TestClientは非同期エンドポイントも同期的に呼び出せる
    response = client.post("/new_session", json=request_body)
    
    # --- 検証 ---
    # ステータスコードが200 OKであることを確認
    assert response.status_code == 200
    
    # レスポンスボディが期待通りであることを確認
    assert response.json() == {
        "message": "New chat session initialized successfully.",
        "project": "new_session_project",
        "phase": "new_session_phase"
    }
    
    # --- モックの呼び出し検証 ---
    # create_or_resume_session が正しい引数で1回呼び出されたことを確認
    # 非同期関数なので assert_awaited_once_with を使う
    mock_create_session.assert_awaited_once_with(phase="new_session_phase", history=None)

# `load_history` 関数のパス (test_history_crud.py にも定義済みだが、重複しないようここに定義)
STORAGE_LOGIC_LOAD_HISTORY_PATH = "app.main.load_history"

@pytest.mark.asyncio
async def test_resume_session_success(mocker):
    """
    POST /resume_session エンドポイントの正常系テスト
    - load_history と create_or_resume_session をモック化する
    - セッションが正常に再開されることを確認する
    """
    # --- モックの設定 ---
    # load_history がダミーの履歴データを返すように設定
    dummy_history_data = {
        "messages": [
            {"role": "user", "content": "履歴からのメッセージ"},
            {"role": "model", "content": "履歴からの応答"}
        ],
        "phase": "resumed_phase",
        "project": "resumed_project",
        "session_id": "resumed_session_123"
    }
    mock_load_history = mocker.patch(
        STORAGE_LOGIC_LOAD_HISTORY_PATH, return_value=dummy_history_data
    )
    
    # create_or_resume_session をモック化
    mock_create_session = mocker.patch(CHAT_LOGIC_SESSION_PATH)
    
    # --- テストデータ ---
    request_body = {
        "project": "resumed_project",
        "phase": "resumed_phase",
        "session_id": "resumed_session_123"
    }
    
    # --- リクエストの実行 ---
    response = client.post("/resume_session", json=request_body)
    
    # --- 検証 ---
    assert response.status_code == 200
    assert response.json() == {"status": "resumed", "message_count": 2}
    
    mock_load_history.assert_called_once_with(
        request_body["project"], request_body["phase"], request_body["session_id"]
    )
    mock_create_session.assert_awaited_once_with(
        phase=dummy_history_data["phase"], history=dummy_history_data["messages"]
    )


@pytest.mark.asyncio
async def test_resume_session_no_history(mocker):
    """
    POST /resume_session エンドポイントの異常系テスト（履歴なし）
    - load_history が空の履歴を返す場合に、セッション再構築が呼ばれないことを確認する
    """
    # --- モックの設定 ---
    # load_history が空の履歴データを返すように設定
    dummy_empty_history_data = {
        "messages": [], # メッセージが空
        "phase": "empty_phase",
        "project": "empty_project",
        "session_id": "empty_session_123"
    }
    mock_load_history = mocker.patch(
        STORAGE_LOGIC_LOAD_HISTORY_PATH, return_value=dummy_empty_history_data
    )
    
    # create_or_resume_session をモック化
    mock_create_session = mocker.patch(CHAT_LOGIC_SESSION_PATH)
    
    # --- テストデータ ---
    request_body = {
        "project": "empty_project",
        "phase": "empty_phase",
        "session_id": "empty_session_123"
    }
    
    # --- リクエストの実行 ---
    response = client.post("/resume_session", json=request_body)
    
    # --- 検証 ---
    assert response.status_code == 200
    assert response.json() == {"status": "no_history", "message": "履歴が存在しません"}
    
    mock_load_history.assert_called_once_with(
        request_body["project"], request_body["phase"], request_body["session_id"]
    )
    # 履歴がないので create_or_resume_session は呼ばれないことを確認
    mock_create_session.assert_not_awaited()