# Generated by Gemini CLI / テストコードを生成させてみた
import pytest
from fastapi.testclient import TestClient
from app.main import app

# TestClientインスタンスを作成
client = TestClient(app)

# `get_histories_list` 関数のパス
STORAGE_LOGIC_GET_HISTORIES_PATH = "app.main.get_histories_list"

def test_get_histories_list_success(mocker):
    """
    GET /projects/{project}/histories エンドポイントの正常系テスト
    - storage_logic.get_histories_list をモック化する
    - 指定したプロジェクトの履歴一覧が正しく返されることを確認する
    """
    # --- モックの設定 ---
    # get_histories_list をモック化し、ダミーの履歴リストを返すように設定
    dummy_histories = [
        {"id": "session1", "phase": "recon"},
        {"id": "session2", "phase": "exploitation"}
    ]
    mock_get_histories = mocker.patch(
        STORAGE_LOGIC_GET_HISTORIES_PATH, return_value=dummy_histories
    )
    
    # --- テストデータ ---
    project_name = "test_project_for_histories"
    
    # --- リクエストの実行 ---
    response = client.get(f"/projects/{project_name}/histories")
    
    # --- 検証 ---
    # ステータスコードが200 OKであることを確認
    assert response.status_code == 200
    
    # レスポンスボディが期待通りであることを確認
    assert response.json() == {"histories": dummy_histories}
    
    # --- モックの呼び出し検証 ---
    # get_histories_list が正しいプロジェクト名で1回呼び出されたことを確認
    mock_get_histories.assert_called_once_with(project_name)

# `load_history` 関数のパス
STORAGE_LOGIC_LOAD_HISTORY_PATH = "app.main.load_history"


def test_load_history_success(mocker):
    """
    POST /load_history エンドポイントの正常系テスト
    - storage_logic.load_history をモック化する
    - 指定した履歴データが正しく返されることを確認する
    """
    # --- モックの設定 ---
    # load_history をモック化し、ダミーの履歴データを返すように設定
    dummy_history_data = {
        "messages": [
            {"role": "user", "content": "最初のメッセージ"},
            {"role": "model", "content": "最初の応答"}
        ],
        "project": "test_project_load",
        "phase": "test_phase_load",
        "session_id": "test_session_load_123"
    }
    mock_load_history = mocker.patch(
        STORAGE_LOGIC_LOAD_HISTORY_PATH, return_value=dummy_history_data
    )
    
    # --- テストデータ ---
    request_body = {
        "project": "test_project_load",
        "phase": "test_phase_load",
        "session_id": "test_session_load_123"
    }
    
    # --- リクエストの実行 ---
    response = client.post("/load_history", json=request_body)
    
    # --- 検証 ---
    # ステータスコードが200 OKであることを確認
    assert response.status_code == 200
    
    # レスポンスボディが期待通りであることを確認
    assert response.json() == dummy_history_data
    
    # --- モックの呼び出し検証 ---
    # load_history が正しい引数で1回呼び出されたことを確認
    mock_load_history.assert_called_once_with(
        request_body["project"], request_body["phase"], request_body["session_id"]
    )

# `delete_history` 関数のパス
STORAGE_LOGIC_DELETE_HISTORY_PATH = "app.main.delete_history"


def test_delete_history_success(mocker):
    """
    DELETE /projects/{project}/histories/{phase}/{session_id} エンドポイントの正常系テスト
    - storage_logic.delete_history をモック化する
    - 指定した履歴が正常に削除されることを確認する
    """
    # --- モックの設定 ---
    # delete_history をモック化し、Trueを返すように設定
    mock_delete_history = mocker.patch(
        STORAGE_LOGIC_DELETE_HISTORY_PATH, return_value=True
    )
    
    # --- テストデータ ---
    project_name = "test_project_delete"
    phase_name = "test_phase_delete"
    session_id = "test_session_delete_456"
    
    # --- リクエストの実行 ---
    # f-stringを使ってURLにパスパラメータを埋め込む
    response = client.delete(f"/projects/{project_name}/histories/{phase_name}/{session_id}")
    
    # --- 検証 ---
    # ステータスコードが200 OKであることを確認
    assert response.status_code == 200
    
    # レスポンスボディが期待通りであることを確認
    assert response.json() == {"deleted": True, "file": f"{phase_name}_{session_id}.json"}
    
    # --- モックの呼び出し検証 ---
    # delete_history が正しい引数で1回呼び出されたことを確認
    mock_delete_history.assert_called_once_with(
        project_name, phase_name, session_id
    )
